# AWS Elastic Beanstalk Configuration
name: skillworld-nexus-lms
type: nodejs:18

build:
  flavor: none

dependencies:
  nodejs:
    npm: "*"

hooks:
  build: |
    npm ci
    npx prisma generate
    npm run build

web:
  commands:
    start: "npm start"
  locations:
    "/":
      root: "public"
      passthru: true
      allow: true

disk: 2048

mounts:
  "/.next":
    source: local
    source_path: next
  "/prisma":
    source: local
    source_path: prisma
