// Test login script
console.log('=== SkillNexus Login Test ===')
console.log('')
console.log('1. Clear browser cache and cookies:')
console.log('   - Press F12 → Application → Storage → Clear site data')
console.log('   - Or use: Ctrl+Shift+Delete')
console.log('')
console.log('2. Test accounts:')
console.log('   Admin: admin@skillnexus.com / Admin@123!')
console.log('   Teacher: teacher@skillnexus.com / Teacher@123!')
console.log('   Student: student@skillnexus.com / Student@123!')
console.log('')
console.log('3. Expected behavior after login:')
console.log('   - Admin → http://localhost:3000/admin/dashboard')
console.log('   - Teacher → http://localhost:3000/teacher/dashboard')
console.log('   - Student → http://localhost:3000/student/dashboard')
console.log('')
console.log('4. If still redirecting to uppowerskill.com:')
console.log('   - Run: npm run dev (restart server)')
console.log('   - Clear .next folder: rmdir /s /q .next')
console.log('   - Check .env file has correct localhost URLs')
console.log('')
console.log('Environment check:')
console.log('NEXTAUTH_URL:', process.env.NEXTAUTH_URL || 'NOT SET')
console.log('NEXT_PUBLIC_URL:', process.env.NEXT_PUBLIC_URL || 'NOT SET')
console.log('NODE_ENV:', process.env.NODE_ENV || 'NOT SET')